frida/frida-gum

gum/backend-darwin/gummemory-darwin.c
The problem before was that if two subregions was contained inside a larger one, you would always get back the address of the first subregion even when the address you were reading from was in the second subregion.
=> Fix reading memory from a subregion in Darwin

gum/backend-darwin/gumprocess-darwin.c, gum/backend-linux/gumprocess-linux.c, gum/backend-qnx/gumprocess-qnx.c, gum/backend-windows/gumprocess-windows.c, gum/gumprocess.h, tests/core/process.c
I have only implemented the function for OS X.
I also added some new test cases for `gum_process_enumerate_ranges` that checks if a given range could be found.
Fixes #20 (at least for OS X).
=> Add gum_process_enumerate_malloc_ranges

gum/backend-linux/gummemory-linux.c, gum/backend-posix/gummemory-posix.c, gum/gummemory-priv.h, gum/gummemory.h
In preparation for having an instance of this function in backend-qnx which behaves differently.
=> Move gum_try_mprotect from backend-posix to backend-linux

gum/backend-qnx/gummemory-qnx.c
This is better for the case where we are changing permissions for
the same page as something we are executing.
=> Make mprotect hack mmap with PROT_EXEC

gum/arch-arm/gumarm.h, gum/arch-arm/gumarmrelocator.c, gum/arch-arm/gumarmrelocator.h, gum/arch-arm/gumarmwriter.c, gum/arch-arm/gumarmwriter.h
Add capstone to the ARM Relocator, allowing for parsing instructions
using the capstone API.
Also, implement rewrite of PC relative ldr instructions (where PC
is the base register for the second operand).
=> Add capstone to armrelocator; implement PC relative ldr rewrite.

tests/core/interceptor.c
The ret variable in this case needs to be volatile so that the
compiler doesn't aggressively optimize, resulting in an assert
0x42 == 0x42.
=> Fix replace_function test case

gum/gumscript-runtime-core.js, tests/core/script.c
This PR adds the following methods to `Memory`
* readShort
* writeShort
* readUShort
* writeUShort
* readInt
* writeInt
* readUInt
* writeUInt
* readLong
* writeLong
* readULong
* writeULong
Not sure what your thoughts are, but I added `longSize` to the top of `gumscript-runtime-core.js` so it's only calculated once, and not each call.
Also, the tests for **\*Long** are missing, I'm not entirely sure how to get the proper sized value for the current platform in C.
=> Add additional shortcuts for reading and writing memory.

tests/core/interceptor.c, tests/gumtest.c, tests/heap/boundschecker.c
Failing tests:
- interceptor/attach_to_heap_api fails with segfault in malloc_init
- script suite fails with segfault when trying to write to stack
- backtracer suite fails with segfault in libfrida-gumpp: _ULarm_dwarf_find_save_locs (libunwind)
- Gum++/Backtracer/can_get_stack_trace_from_invocation_context fails assertion (return_addresses.len >= 1): (0 >= 1)
- boundschecker/output_report* tests hang the process
=> Fix bugs in gumarmrelocator and gumarmreader related to improper instruction assembly/decoding.

bindings/gumjs/gumscript-runtime-core.js, bindings/gumjs/gumscriptcore.cpp
We should probably also implement `ptr1.equals(ptr2)`, but we can do that in javascript, by using `ptr1.cmp(ptr2) === 0`.
=> Add NativePointer.cmp for comparing pointers

bindings/gumjs/gumscript-runtime-dalvik.js
It's useful:
- if you have a reference to an object and you don't know the class of it
- if you call a generic method in Java and you want to determine the class of the result
- to determine the real class if it's type is an interface
```
...
let instance = Dalvik.cast(p, klass);
console.log(instance.constructor.name);
console.log(instance.class);
console.log(Dalvik.getObjectClassname(instance));
console.log(Dalvik.getObjectClassname(p));
```
Results
```
ITest
interface com.example.example.ITest
com.example.example.Test1
com.example.example.Test1
```
=> Get object classname

gum/backend-qnx/gumprocess-qnx.c
This is the way that the dynamic linker itself looks up symbols, as there is no .dynamic section in a stripped QNX binary.
=> Use PT_DYNAMIC to enumerate dynamic symbols on QNX

bindings/gumjs/gumscript-runtime-dalvik.js
It's possible that 'toJni' or 'fromJni' throws an error so we have to ensure that env.popLocalFrame(...) will be called anyway.
=> Ensure env.popLocalFrame will be called

bindings/gumjs/gumscript-runtime-dalvik.js
- 'isCompatible' functions improved
- Using functionnames
- Add 'Env.prototype.javaLangString'
I really don't know why there wasn't 'Env.prototype.javaLangString' already implemented.
=> Some improvements

bindings/gumjs/gumscript-runtime-dalvik.js, bindings/gumjs/gumscriptbundle.h
- add `Dalvik.synchronized(obj/objHandle, fn);`. It's almost equivalent to following Java code `synchronized (obj) { fn(); }`
- add `Dalvik.scheduleOnMainThread(fn);`
- if we set an implementation to `null`, set it really to `null`
- add `Dalvik.isMainThread()`. Now we can check if we are in the main thread
- refactoring: assertions
- increase GUM_MAX_SCRIPT_SOURCE_CHUNKS to 6
=> `Dalvik.synchronized`, `Dalvik.scheduleOnMainThread` and `Dalvik.isMainThread` implemented

bindings/gumjs/gumscript-runtime-java.js
```Java.openDexFile(filePath)``` will return an object with two methods
- ```load()```: load the dex-file
- ```getClassNames()```: get the class names
=> Implement method to load classes at runtime

bindings/gumjs/gumv8memory.cpp, gum/backend-windows/gummemoryaccessmonitor-windows.c, gum/gummemoryaccessmonitor.h, tests/core/memoryaccessmonitor-fixture.c
Also add an auto-reset switch that can be used to monitor all the access
or only the first one.
Sorry, no new tests for this feature but it passes all the olds ones.
=> Add the possibility to monitor any combination of R, W or X operations

gum/backend-qnx/gumprocess-qnx.c
Currently this implementation uses a vfork to spawn a new process which can then inspect the threads of the original process, as inspecting the currently running process with procfs is broken on qnx
=> Implement enumerate_threads and modify_thread for qnx

bindings/gumjs/Makefile.am, bindings/gumjs/gumdukmacros.h, bindings/gumjs/gumdukscript.c, bindings/gumjs/gumdukstream.c, bindings/gumjs/gumdukstream.h, bindings/gumjs/gumjs-32.vcxproj.filters, bindings/gumjs/gumjs-64.vcxproj.filters, bindings/gumjs/gumjs-common.props, bindings/gumjs/gumjs-core.js, bindings/gumjs/gumv8script-priv.h, bindings/gumjs/gumv8script.cpp, bindings/gumjs/gumv8stream.cpp, bindings/gumjs/gumv8stream.h, configure.ac, tests/gumjs/script.c
For now we only expose constructors for the lowest level streams that
allow working with file-descriptors (UNIX) and HANDLEs (Windows), but
the JavaScript wrappers can obviously be used with any GInputStream and
GOutputStream implementation.
=> Add stream APIs for working with GIO streams

bindings/gumjs/gumjs-java.js
tech/yusi/fridademo/Jingdong.java
`public class Jingdong {
public static String a(String arg0, String arg1)   { return arg0 + arg1;  }
public static int a(int arg0, int arg1)  {   return arg0 + arg1;   }
}`
frida js
`Java.perform(function () {
var Jingdong = Java.use("tech.yusi.fridademo.Jingdong");
var ret = Jingdong.a(1, 2);
send(ret);
}
`
It works well
if change Jingdong.java, remove one static 
`public class Jingdong {
public String a(String arg0, String arg1)   { return arg0 + arg1;  }
public static int a(int arg0, int arg1)  {   return arg0 + arg1;   }
}`
It  complains:
Error: a: cannot call instance method without an instance
In fact, 
Jingdong.a.overload('int', 'int').type is staic
Jingdong.a.overload("java.lang.String", "java.lang.String").type is instaic, 
methods[0]  == …
=> Check method type just for the invoked method, instead of method[0]

bindings/gumjs/gumjs-core.js
hexdump() is now reversible with "xxd -r"
=> Remove "0x" prefix from hexdump offsets

bindings/gumjs/gumdukcore.c, bindings/gumjs/gumdukcore.h, bindings/gumjs/gumdukinterceptor.c, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8core.h, bindings/gumjs/gumv8interceptor.cpp, tests/gumjs/script.c
One shortcoming of NativeFunction is that it is not possible to get
`errno` / `GetLastError()` reliably, as Frida may have clobbered it.
This new API is just like NativeFunction except that the return value
is an object containing `value` and `errno` (or `lastError` on Windows).
For example calling `open()` with a path that does not exist, the return
value on Darwin would be:
{ value: -1, errno: 2 /* ENOENT */ }
=> Add SystemFunction API

bindings/gumjs/Makefile.am, bindings/gumjs/gumdukcore.c, bindings/gumjs/gumdukcore.h, bindings/gumjs/gumjs-32.vcxproj.filters, bindings/gumjs/gumjs-64.vcxproj.filters, bindings/gumjs/gumjs-common.props, bindings/gumjs/gumsourcemap.c, bindings/gumjs/gumsourcemap.h, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8core.h, bindings/gumjs/runtime/error-handler.js, bindings/gumjs/runtime/index.js
A typical source map takes ~5 seconds to parse with the Duktape runtime
on an iPhone 5S. This is way too slow, and there isn't much room for
optimizing the algorithm due to the sheer amount of bytes that need to
be munged. To solve this we implement a minimal source map parser in C
that only covers the bits that we need.
=> Fix performance issue with source maps

bindings/gumjs/generate-runtime.py, tests/gumjs/script.c
Depends on: https://github.com/frida/frida-compile/pull/2
frida-compile now, by default, encodes source locations relative to where its invoked, not where the scripts live. This ensures that a debugger can correctly resolve paths using the frida-compile invocation site as the root directory.
So with that, `../node_modules` handling is no longer required. For an input script `runtime\foo.js` that calls `require ('promiscuous')`, frida-compile will resolve to `node_modules/promiscuous`. The path then, as before, gets appended to a pseudo-fs-root `frida/`. To keep things tidy (and reduce debugger confusion), the path also has its slashes tweaked to fit canonical form.
=> Accommodate sourcemap changes in frida-compile/pull/2

bindings/gumjs/gumdukmemory.c, bindings/gumjs/gumv8memory.cpp, tests/gumjs/script.c
Aligns smaller (less than page size) allocations with behavior of larger ones (i.e. zero initializes all the time). Sub-ms perf impact measured.
Smaller allocations are now zero-initialized via `g_malloc0`.
Verified larger allocations are already zero-initialized across all the major platforms:
- Windows
- `VirtualAlloc` with `MEM_COMMIT`
- Linux
- `mmap` with `MAP_ANONYMOUS`
- Mac
- `mach_vm_allocate` ([source](https://opensource.apple.com/source/xnu/xnu-1456.1.26/osfmk/vm/vm_user.c)) 
Test added to catch any outliers.
=> Ensure smaller allocations of memory are zero-initialized

gum/backend-arm64/gumstalker-arm64.c, gum/backend-darwin/gumtls-darwin.c, gum/backend-posix/gumtls-posix.c, gum/backend-qnx/gumtls-qnx.c, gum/backend-windows/gumtls-windows.c, gum/backend-x86/gumstalker-x86.c, gum/gum.c, gum/guminterceptor.c, gum/gumtls.h, libs/gum/prof/gumcallcountsampler.c, tests/core/tls.c
Also get rid of the destructor support in GumTls, and rely on GPrivate
for such use-cases. Using GPrivate was previously not possible as any
intercepted function might be called from one of the application's own
thread-local storage destructor functions. Given how such destructors
are called in an unpredictable order, this would typically result in
memory leaks, where our own storage was allocated again right after
getting destroyed.
=> Update to the new GThread API

gum/backend-arm64/gumstalker-arm64.c
Tested on Samsung S6 Edge Android API 24.
Executing a load pair instruction that use the same register for both register operands results in Illegal Instruction error.
Using a second register (X15) as second register operand, even if not used later in the code, fixes it.
=> Fixed illegal instruction for physical devices

Makefile.am, gum/backend-arm64/gumstalker-arm64.c
Gdbserver based on tcp:PORT instead of files in order to properly work with gdb and target remote.
=> Android gdbserver

bindings/gumjs/runtime/core.js, gum/backend-arm64/gumstalker-arm64.c, gum/backend-x86/gumstalker-x86.c, gum/gumevent.h
- `compile` events are emitted as soon as a basic block gets compiled by the Stalker. This happens once per block, so it's useful to understand which parts of code gets executed but it's not a full live trace of the execution.
- `block` events are emitted each time a basic block is executed, so can be used to actually trace the execution.
=> Add block and compile events to Stalker

tests/core/arch-x86/stalker-x86.c
Stalking a function using 'repne jb' currently causes frida-gum to generate invalid code.
=> Add testcases for repne jb (failing) and repne ret

gum/gum.c
Currently `debug()` strings go to stdout/stderr on Windows, which means they're usually not visible.
=> Add OutputDebugString() to debug() strings on Windows

bindings/gumjs/gumdukinstruction.c, bindings/gumjs/gumv8instruction.cpp
This ensures in a naive way that the capstone instance is created on all code paths which need it.
=> Create capstone instance during module initialization

gum/arch-x86/gumx86writer.c, gum/arch-x86/gumx86writer.h
- make sub_reg_reg compatible with 64-bits registers, by adding REX prefix
- cmp_reg_reg is exactly the same, with different opcode
=> Fix x86writer’s sub_reg_reg, add cmp_reg_reg

gum/backend-darwin/gumprocess-darwin.c
This is needed to avoid stalking threads at address 0, causing exceptions and / or deadlocks. At most it tries for 20 seconds, then gives up.
=> Poll thread state if instruction pointer is NULL

bindings/gumjs/gumdukdatabase.c, bindings/gumjs/gumv8database.cpp, bindings/gumjs/runtime/core.js, tests/gumjs/script.c
Example: `SqliteDatabase.open(fileName, {flags: [‘readwrite’, ‘create’]})`
Possible flags are `readonly`, `readwrite`, `create`. The `create` flag can be combined only with `readwrite`. The default flags are `[‘readwrite’, ‘create’]`.
=> Expose sqlite open flags

bindings/gumjs/gumdukmodule.c, bindings/gumjs/gumv8module.cpp, gum/gummodulemap.c, gum/gummodulemap.h
It returns a copy of the current internal `modules` array. Example:
```
var mm = new ModuleMap();
mm.values(); // get a copy of current modules array
```
=> Expose ModuleMap values() method

gum/backend-elf/gumelfmodule.c
bloom_shift is initialized but not used, that makes the compiler sad (-Wunused-but-set-variable)
=> remove unused variable in gumelfmodule.c

bindings/gumjs/gumdukvalue.c, bindings/gumjs/gumv8process.cpp, gum/backend-darwin/gumprocess-darwin.c, gum/backend-linux/gumprocess-linux.c, gum/backend-qnx/gumprocess-qnx.c, gum/gumprocess.h
The tail of file-mapped segments is guaranteed to be accessible only within “vm_kernel_page_size” boundary after the end of file, after that point SIGBUS is triggered - regardless of the real size of the memory map.
The returned “size” for ranges crossing the end of mapped files is now adjusted to be within the safe range.
As a plus, “file” object has the new “size” field which holds the size of the mapped file on disk in bytes.
Added the “file” object to “Module.enumerateRanges()”  results too.
__PAGEZERO segment is now skipped while enumerating Module’s ranges.
=> Adjust size of mapped ranges (darwin)

gum/backend-darwin/gumdarwinmodule.c
- because they’ll have different values for `slot`
=> Allow emitting i/macOS imports more than once per symbol

gum/backend-darwin/gumcodesegment-darwin.c, gum/backend-darwin/gummemory-darwin.c, gum/backend-posix/gummemory-posix.c, gum/backend-windows/gummemory-windows.c, gum/gum.c, gum/gumcodeallocator.c, gum/gummemory.h, gum/gummetalarray.c
This should be used to get the full extent of ranges allocated using `gum_alloc_n_pages` including the overhead (mostly useful for cloaking). This is implemented in the various backends.
=> Add gum_query_page_allocation_range

gum/backend-darwin/gumprocess-darwin.c, gum/backend-linux/gumprocess-linux.c, gum/backend-qnx/gumprocess-qnx.c, gum/backend-windows/gumprocess-windows.c, gum/gum.c, gum/gumdefs.h, gum/gumprocess.h, vapi/frida-gum-1.0.vapi
Implemented only on i/macOS for now.
The default behaviour when apple’s libpthread allocates resources for a thread is to create a contiguous range made of guard + stack + pthread. There’s also the possiblity to create a thread providing a separated stack, in that case no guard page will be provided by default and only the pthread structure will be allocated internally.
In any case, both the internal allocation extents and the stack itself can be retrieved by picking the right values out of the opaque pthread structure.
The `gum_thread_try_get_ranges` function detects if the allocation is contiguous or not. If it’s contiguous only one range is filled, otherwise there will be one range for stack and one for pthread structure. The number of produced ranges is returned. In backends which …
=> Potentially cloak more than one range for threads

gum/backend-elf/gumelfmodule.c
DT_GNU_HASH is not available on all ELF platforms and it is a GNU extension.
This corrects a build on NetBSD/amd64 8.99.12.
=> Skip DT_GNU_HASH in gum_store_symtab_params if unavailable

bindings/gumjs/gumdukstream.c, bindings/gumjs/gumv8stream.cpp, bindings/gumjs/runtime/core.js
to stream directly from memory without making copies of the data
=> Add OutputStream.writeMemoryRegion

bindings/gumjs/generate-bindings.py
Added replace("\r", "") after reading gum headers contents to avoid issues with different OS/git configurations.
=> Added carriage return replacing

gum/backend-darwin/gumcodesegment-darwin.c
When realize could fail, avoid it entirely and directly remap the segment. This works where code signing isn’t an issue but sandboxing breaks executable file mapping (like Electra on iOS 11.1.2).
=> Realize if supported, remap otherwise

gum/backend-darwin/gumexceptor-darwin.c
This is to avoid corrupting `old_ports->count` while the worker thread is potentially iterating on it. That could have produced an infinite loop in the worker thread leading to indefinite hang or memory corruption.
=> Stop worker thread before modifying old_ports

bindings/gumjs/gumdukkernel.c, bindings/gumjs/gumv8kernel.cpp, gum/backend-darwin/gumkernel-darwin.c, gum/gumkernel.c, gum/gumkernel.h
- make gum_kernel_read failsafe by reading in chunks smaller than page size
- add Kernel.alloc(), Kernel.protect(), and Kernel.pageSize
obviously Kernel.protect() is a bit crippled because to really change to any protection it's required to patch parent page table entries too, but getting there!
=> Improve Frida Kernel

gum/gummemory-priv.h, gum/gummemory.c, gum/gummemory.h, tests/core/memory.c
The mask is bitwise AND-ed against both the needle and the haystack.
To specify the mask it's now possible to append a `:` char after the needle, then the mask with the same syntax (radare2-style), example:
```
Memory.scanSync(address, size, "13 37 13 37 : 1f ff ff f1");
```
As a plus it's now possible to specify nibble-level wildcards, which are translated to masks under the hood, example:
```
Memory.scanSync(address, size, "?3 37 13 ?7");
```
Obviously this kind of search introduces a bit of overhead, but the design principle is to avoid all overhead when not actually using masks.
=> Add memory search with mask

gum/backend-linux/gumprocess-linux.c
We don't need these with the proper toolchains available. Part of fixing mips support.
=> Removed unnecessary (and bug inducing) definition of getcontext and setcontext

gum/backend-darwin/gumcodesegment-darwin.c
Instead of failing the assertion, that will let the try_realize fail and take the alternative path before giving up.
This is enough to fix attach to `com.apple.WebKit.*` processes on iOS 11.x
=> Let gum_file_open_tmp fail

gum/backend-linux/gumprocess-linux.c
g_file_get_contents allocates buffer for /proc/$pid/auxv file and it was not freed
=> Free linux auxv struct

bindings/gumjs/gumdukinstruction.c, bindings/gumjs/gumv8instruction.cpp, tests/gumjs/script.c
Look here: https://github.com/frida/frida-gum/issues/293
I tested the patch using ducktape on a x86 binary and it's ok.
My test build is python-64.
You should test all the other architectures and also the v8 patch, I didn't find how to select v8 in the compilation process.
Here an example:
```python
>>> import frida
>>> 
>>> code = """
... i = Instruction.parse(ptr("0x4005C7")) //movzx   eax, byte ptr [rax]
... console.log(JSON.stringify(i.operands))
... """
>>> pid = frida.spawn(["./foo", "A"*30])
>>> session = frida.attach(pid)
>>> script = session.create_script(code)
>>> script.load()
[{"type":"reg","value":"eax","size":4},{"type":"mem","value":{"base":"rax","scale":1,"disp":0},"size":1}]
>>> 
```
=> add size field to Instruction.operands

gum/backend-arm64/guminterceptor-arm64.c
Modified the arm64 relocator to use `x18` instead of `x16` since `x18` is actually unreserved.
`x16` is used for supervisor calls so when we clobber it we can cause applications to crash. 
E.g. using interceptor with the address of an svc instruction will clobber the syscall value held in `x16`.
@oleavr this works, have tried and tested it and I can now see the values in x18 instead, also x16 remains unclobbered. I'm not sure if all of the replacements were necessary, i'll let you comment since you're the brains 😄.
As discussed previously, there is definitely a more elegant way to preserve state without clobbering registers but this works for now. I think `x18` is definitely most suitable for iOS at least.
=> ARM64 relocator x16 to x18 migration

bindings/gumjs/gumdukcore.c, bindings/gumjs/gumdukcore.h, bindings/gumjs/gumdukscript.c, bindings/gumjs/gumdukscriptbackend.c, bindings/gumjs/gumdukscriptbackend.h, bindings/gumjs/gumscriptbackend.c, bindings/gumjs/gumscriptbackend.h, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8scriptbackend.cpp, vapi/frida-gumjs-1.0.vapi
- Provide a way to run some code with a ScriptBackend's lock held,
and a way to check if the lock is currently held.
- Consolidate Duktape locking to one lock like on V8.
- Fix V8 unlock logic when an exception occurs.
=> Add GumJS locking API and rework locking

bindings/gumjs/gumdukmodule.c, bindings/gumjs/gumv8module.cpp
Because internally it’s calling dlopen which in turn can lock on dyld lock, causing a deadlock.
Example deadlock stack trace excerpt:
```
Thread 6
0   libsystem_pthread.dylib         _pthread_mutex_lock_wait
1   libsystem_pthread.dylib         _pthread_mutex_lock_slow$VARIANT$mp
2   frida-agent.dylib               _gum_duk_scope_enter (gumdukcore.c:1138)
3   frida-agent.dylib               gum_duk_invocation_listener_on_leave (gumdukinterceptor.c:697)
4   frida-agent.dylib               _gum_function_context_end_invocation (guminterceptor.c:1360)
5   libsystem_kernel.dylib          write
6   MyApp                           0x429e68
...
Thread 7
0   libsystem_pthread.dylib         _pthread_mutex_lock_wait
1   libsystem_pthread.dylib         _pthread_mutex_lock_slow$VARIANT$mp
2 …
```
=> Let the js lock go before calling gum_module_ensure_initialized

bindings/gumjs/runtime/hexdump.js
I have only tested this on 32bits. So using the `NativePointer.toInt32()` works. Not sure how this should work on 64-bits adressing. I'm also not sure why NativePointer will only return signed integers. Isn't it more logical to return an unsigned int?
=> Show the actual start address when viewing a pointer.

meson.build
If the options enable_gumpp and enable_gumjs in meson_options.txt are set to false, it will fail to compile as have_v8 is undefined.
=> Fix have_v8 undefined

bindings/gumjs/gumdukkernel.c, bindings/gumjs/gumv8kernel.cpp, bindings/gumjs/types/frida-gum/frida-gum.d.ts
Same semantics as `Memory.read*` / `Memory.write*` - except the fact that `read*String` functions require the `length` second parameter for now.
=> Add Kernel typed read/writes

bindings/gumjs/gumdukcore.c, bindings/gumjs/gumdukcore.h, bindings/gumjs/gumdukkernel.c, bindings/gumjs/gumdukvalue.c, bindings/gumjs/gumdukvalue.h, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8core.h, bindings/gumjs/gumv8kernel.cpp, bindings/gumjs/gumv8value.cpp, bindings/gumjs/gumv8value.h, bindings/gumjs/types/frida-gum/frida-gum.d.ts, gum/backend-darwin/gumkernel-darwin.c, gum/gumkernel.c, gum/gumkernel.h
- try the unslid base first if kernel seems being debugged
- make `Kernel.base` writable to override the internal base-finding algorithm
Plus:
- add `Kernel.free` to deallocate memory allocated with `Kernel.alloc`
- tweak the `Int64` / `UInt64` typescript type definitions to expose `.not()` and `.equals()`
- remove dupe type definitions for `Kernel.readByteArray()` / `Kernel.writeByteArray()`
=> Improve Kernel APIs to support weird iOS kernels

gum/backend-darwin/gumdarwinmapper.c, gum/backend-darwin/gumdarwinmodule.c, gum/backend-darwin/gumdarwinmodule.h, gum/backend-darwin/gumdarwinmoduleresolver.c, gum/backend-darwin/gumkernel-darwin.c, vapi/frida-gum-darwin-1.0.vapi
- add _enumerate_dependencies api call
- add the “header-only” property, to load only the header and the commands instead of the whole binary, applies to file system loading
- enable gumdarwinmodule to load executables too, not only libs
=> Tweak darwinmodule for quick app check

gum/backend-darwin/gumprocess-darwin.c
In recent libpthread, as of iOS 12.x, that field became `stackbottom`, the rest of the fields we care about are still valid. In this way there’s no need to add complexity to figure out the flavor of the structure (at least just yet).
=> Fix gum_thread_try_get_ranges() on latest Apple OSes

bindings/gumjs/runtime/hexdump.js
'hexdump()' will throw an error when option's length bigger than ArrayBuffer.length.
=> 'hexdump()' has error when option's length bigger than ArrayBuffer.length

gum/backend-arm64/gumstalker-arm64.c, tests/core/arch-arm64/stalker-arm64.c
This still does not work but the idea is as follows, let me know how it looks like to you or if you think otherwise.
`gum_stalker_iterator_keep` it emits new code when SVC calls are found to check for clone calls. When this happen, `ctx->thread_clone` is set with `GUM_NEW_THREAD_WHILE_STALKING`. Likewise, after encountering a SVC call afterwards is inserted more code to check if the SVC call was clone to get the new thread id of the child - `gum_stalker_thread_creation` is where child and parent is distinguished. Is here where I would like to return to normal life for the child and within the parent notify with a new event so the user can decide whether or not wants to stalk the new thread. However, I am failing to do so - I dunno how to 'disinfect' the child and leave untouched the …
=> Clone fix for arm64 android

bindings/gumjs/runtime/message-dispatcher.js, tests/gumjs/script.c
Multiple threads can now wait on the same message type. At every incoming message one thread at a time gets woken up in a FIFO fashion. As a plus, it makes sure no exceptions thrown from the wait callback could cause an infinite wait.
Added also a test case for this scenario.
=> Fix parallel wait

gum/backend-linux/gumandroid.c
Per https://github.com/frida/frida/issues/1026 and https://github.com/frida/frida-gum/pull/354 -
I looked into how the linker is meant to be established in Android going forward. According to
https://source.android.com/devices/architecture/modular-system/runtime#bionic-changes - Google
intends to maintain both `/system/bin/linker` and `/system/bin/linker64` as a symlink, pointing
to what the real file will be.
This means if we look for those files and they are symlinks, the linker should be mapped to memory
using the files realpath. So for future changes, looking to see what the symlink resolves as should
make this work in all future version (and keep its backwards compatibility).
Tested this on Android 5, 7.2, 8.0.1, 9 and 10.
=> Make frida-gum linker seeking future-proof on Android

bindings/gumjs/gumdukmemory.c, bindings/gumjs/gumdukmemory.h, bindings/gumjs/gumdukvalue.c, bindings/gumjs/gumdukvalue.h, bindings/gumjs/gumv8memory.cpp, tests/gumjs/script.c
This enable AccessMonitor on V8 for linux and duktape runtime implementation.
Do not review nor merge until https://github.com/frida/frida-gum/pull/352 gets pushed to master.
=> Enable AccessMonitor V8 for Linux and implement support for duktape runtime

gum/backend-darwin/gumprocess-darwin.c
Use the same fix used in https://github.com/frida/frida-gum/pull/352 for Darwin ARM devices - I don't have any to test but it should work.
=> Handle correctly arm/thumb when restoring exception on Darwin

bindings/gumjs/gumdukmemory.c, bindings/gumjs/gumv8memory.cpp, bindings/gumjs/runtime/core.js, tests/gumjs/script.c
Useful if you want to avoid needing to constantly use .writeByteArray(...). Might solve #320.
=> Add NativePointer#mapByteArray()

gum/backend-darwin/gumexceptor-darwin.c
So that it's used as maximum size for output arrays. The semantics of this in/out argument is the same in `task_get_exception_ports` and `task_swap_exception_ports`.
Excerpt from the man page:
> [pointer to in/out scalar]
On input, the maximum size of the array
buffers; on output, the number of returned <exception type mask,
exception port, behavior, flavor> sets returned.
=> Honor masks_count also as input argument

bindings/gumjs/gumdukscript.c, bindings/gumjs/gumv8script.cpp
This ensures that ultimately the script core is disposed, which in turn disposes its reference to the exceptor.
Failing to do so caused indefinite hang when attaching after detaching in presence of unloaded scripts, for the exceptor thread remaining in the target process.
=> Ensure script context is destroyed even if the script is still unloaded

gum/backend-libdwarf/gumsymbolutil-libdwarf.c
GUM previously relied upon 'dladdr' to find symbol names when trying to make a debug symbol from an address. This only works when symbols are in the .dynamic section. It will not incorporate those in the .symtab section.
The dwarf engine already walks the .symtab and .dynamic section to build a hashtable indexed on names to lookup addresses.This patch builds a hashtable of the reverse, but only for the .symtab section (we can rely on the existing implementation working for .dynamic). We can then use this hash table to do the reverse lookup.
This issue will not affect binaries built with -rdynamic, and may also not affect those built with -pie. Obviously, this doesn't affect shared objects by their nature.
=> Improve address resolution in the libdwarf backend

gum/backend-posix/gumexceptor-posix.c
Code was previously using a value of 0d150 = 0x96 as the CPSR mask to determine whether it was running in ARM mode.
/// Group of ARM instructions
typedef enum arm_insn_group {
ARM_GRP_INVALID = 0, ///< = CS_GRP_INVALID
// Generic groups
// all jump instructions (conditional+direct+indirect jumps)
ARM_GRP_JUMP,	///< = CS_GRP_JUMP
ARM_GRP_CALL,	///< = CS_GRP_CALL
ARM_GRP_INT = 4, ///< = CS_GRP_INT
ARM_GRP_PRIVILEGE = 6, ///< = CS_GRP_PRIVILEGE
ARM_GRP_BRANCH_RELATIVE, ///< = CS_GRP_BRANCH_RELATIVE
// Architecture-specific groups
ARM_GRP_CRYPTO = 128,
ARM_GRP_DATABARRIER,
ARM_GRP_DIVIDE,
ARM_GRP_FPARMV8,
ARM_GRP_MULTPRO,
ARM_GRP_NEON,
ARM_GRP_T2EXTRACTPACK,
ARM_GRP_THUMB2DSP,
ARM_GRP_TRUSTZONE,
ARM_GRP_V4T,
ARM_GRP_V5T,
ARM_GRP_V5TE,
ARM_GRP_V6,
ARM_GRP_V6T2,
ARM_GRP_V7,
ARM_GRP_V8, …
=> Fix flags for CPSR thumb detection

gum/arch-arm/gumthumbrelocator.c, tests/core/arch-arm/thumbrelocator.c
Just borrow the variable `self->it_block.active` as a flag.
=> Fix ThumbRelocator IT block eoi logic

gum/backend-darwin/gumdarwinsymbolicator.c, gum/gumdefs.h
Also bump max symbol name length to 2048.
C++ types are really chatty, so symbols like `IPC::callMemberFunctionImpl<WebKit::WebPageProxy, void (WebKit::WebPageProxy::*)(WTF::ObjectIdentifier<WebCore::FrameIdentifierType>, WebCore::SecurityOriginData&&, WebCore::PolicyCheckIdentifier, unsigned long long, WebKit::NavigationActionData&&, WebKit::FrameInfoData&&, WTF::Optional<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType> >, WebCore::ResourceRequest const&, WebCore::ResourceRequest&&, IPC::FormDataReference&&, WebCore::ResourceResponse&&, WebKit::UserData const&, unsigned long long), std::__1::tuple<WTF::ObjectIdentifier<WebCore::FrameIdentifierType>, WebCore::SecurityOriginData, WebCore::PolicyCheckIdentifier, unsigned long long, WebKit::NavigationActionData, …
=> Fix handling of long symbol names

bindings/gumjs/gumv8module.cpp
This ensures correct handling of non-english/non-latin module names, and matches what already happens in other module-related APIs and in duktape.
=> Use utf8 for ModuleMap.values() name field in v8

gum/arch-arm/gumthumbwriter.c, gum/arch-arm/gumthumbwriter.h, gum/backend-arm/gumstalker-arm.c, tests/core/arch-arm/stalker-arm.c
This fix adds a `thumb_interworking` flag to `_GumBranchDirectRegOffset`. This type is used during MOV, ADD, SUB and BX instruction handling. It's value is set `false` except for `BX` instructions. It's value should be considered meaningful only during Thumb operation.
Whilst its value is set in `gum_stalker_get_target_address` which is used in both ARM and Thumb modes, it is only used in 
`gum_exec_ctx_write_thumb_mov_branch_target` and not `gum_exec_ctx_write_arm_mov_branch_target` and hence any setting of this value in `gum_stalker_get_target_address` when operating in ARM mode is benign.
Similarly, the value is set in `gum_exec_block_write_thumb_handle_kuser_helper` and not in `gum_exec_block_write_arm_handle_kuser_helper`.
=> Fix ARM Stalker mov pc, <reg> Thumb interworking

gum/arch-arm64/gumarm64writer.c
PACed ptrs need to be stripped also on macOS arm64e.
=> Update gumarm64writer.c to make it compatible with macOS ARM

gum/backend-linux/gumlinux.h, gum/backend-linux/gumprocess-linux.c, tests/core/process.c
Fix for #464. Implementation changed to expose a test seam in lieu of a mocking framework. Logic corrected.
=> Fix architecture detection on big-endian systems

gum/backend-linux/gumprocess-linux.c, gum/backend-qnx/gumprocess-qnx.c
The libc is currently detected by checking for the 'exit' symbol.
Whichever shared library contains a function named 'exit' could
falsely be detected to be the libc. This commit adds another check
for the '__libc_start_main' symbol which should be more libc-specific.
As a minimal example which shows the bug, the following program
crashes when frida attaches:
#include <stdio.h>;
void exit(int i) {
printf("foo");
}
int main(int argc, char** argv) {
printf("Hi!\n");
getchar();
printf("bye!\n");
return 0;
}
If the libc_start_main symbol is not found, the old check for the exit function
will still happen - so this patch shouldn't make things worse, right?
=> Better discovery of the libc for linux and qnx.

gum/backend-arm/gumstalker-arm.c, gum/backend-arm64/gumstalker-arm64.c, gum/backend-x86/gumstalker-x86.c, gum/gumeventsink.c, gum/gumeventsink.h, tests/core/arch-arm/stalker-arm.c, tests/core/arch-arm64/stalker-arm64.c, tests/core/arch-x86/stalker-x86.c
~~This PR is still in the proposal phase as I haven't added ARM64 or MIPS support nor reasonable tests.~~
For background: in my personal project hotwax, my [`event_sink.c`](https://github.com/meme/hotwax/blob/master/src/event_sink.c) simply acts as a stub which does nothing (and returns a query_mask of 0). Now, in another project where I use the Frida Stalker, I've run into the same problem: I do not need an EventSink, but are required to provide one.
So, I propose that we allow EventSink to be `NULL` so that a user can provide ONLY a transformer and nothing else. Or alternatively, they can provide no Transformer or EventSink (not sure what the use-case is for this, but it is now allowed)
So my goals for this PR are _speed_. I want to provide reasonable speed benefits if you do not …
=> Support a NULL EventSink in Stalker

gum/arch-arm64/gumarm64relocator.c
By checking also for arm64e variants of RET and BR.
=> Fix arm64e support in relocator

bindings/gumjs/gumquickcore.c, bindings/gumjs/gumquickcore.h, bindings/gumjs/gumquickprocess.c, bindings/gumjs/gumquickscriptbackend-priv.h, bindings/gumjs/gumquickscriptbackend.c, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8core.h, bindings/gumjs/gumv8process.cpp, bindings/gumjs/gumv8scope.cpp, bindings/gumjs/gumv8scope.h, bindings/gumjs/gumv8scriptbackend.cpp, bindings/gumjs/gumv8scriptbackend.h, gum/gumexceptor.c, gum/gumexceptor.h, gum/gumprocess.h, tests/gumjs/script-fixture.c, tests/gumjs/script.c
- use the exceptor to detect this condition
- when that happens, the scope mutex is marked as "trapped" in the backend
- in this condition the mutex remains locked, but `with_lock_held` won't block
- so that the `ThreadSuspendMonitor` doesn't create deadlocks
- also, all JS exception handlers are skipped in this state
This will allow crashes of this kind to actually surface instead of causing a deadlock. 
This can be improved over time, but for how this is implemented right now it's not really possible to "catch" and handle this kind of exceptions, because that would require forcibly unlock the scope mutex even if it belongs to a crashed thread.
The test case runs in "slow" mode only
```
gum-tests -m slow -p /GumJS/Script/crash_on_thread_holding_js_lock_should_not_deadlock#V8
gum-tests -m …
```
=> Fix deadlock when the thread holding the JS lock crashes

config.h.in, gum-32.vcxproj.filters, gum-64.vcxproj.filters, gum-common.props, gum/backend-darwin/gummemory-darwin.c, gum/gum.c, gum/gumdarwinmodule.c, gum/gumdarwinmodule.h, gum/gumdefs.h, gum/gumenumtypes.c.template, gum/gumenumtypes.h.template, gum/gumexceptor.h, gum/gumprocess.c, gum/gumprocess.h, gum/meson.build, meson.build, tests/core/interceptor.c, tests/gum-tests.vcxproj, tests/gumtest.c, tests/prof/sampler.c
This PR adds support for linking against a system GLib, as well as adds support for building GObject Introspection files (if the user has the required tools installed on their system).
The Frida build system HAS NOT been updated to support this change as more work is planned for that. However, it's straightfoward to test:
```diff
legacy_includes="-I$FRIDA_PREFIX/include"
-legacy_libpaths="-L$FRIDA_PREFIX/lib"
+#legacy_libpaths="-L$FRIDA_PREFIX/lib"
if [ "$FRIDA_ENV_SDK" != 'none' ]; then
legacy_includes="$legacy_includes -I$FRIDA_SDKROOT/include"
-  legacy_libpaths="$legacy_libpaths -L$FRIDA_SDKROOT/lib"
+  #legacy_libpaths="$legacy_libpaths -L$FRIDA_SDKROOT/lib"
fi
CPPFLAGS="$CPPFLAGS $legacy_includes"
-LDFLAGS="$LDFLAGS $legacy_libpaths"
+#LDFLAGS="$LDFLAGS $legacy_libpaths" …
```
=> Support linking against system GLib

gum/meson.build, meson.build
During set-up I ran into another bug that I somehow missed in the original PR.
When linking against `libelf` and `libdwarf` using `extra_libs_private` it will only add `-lelf` and `-ldwarf`. However this apparently doesn't do what I thought it did so you'll get a bunch of errors for missing symbols in `libelf`.
It turns out that `g-ir-scanner` expects _instead_ to receive e.g.: `--extra-library=elf`. By using `dependency` and having it link against `gum` (via `extra_deps`) Meson will automatically add `--extra-library=elf`.
So we can either use a `dependency`, or we can add the `--extra-library=` flags manually into `extra_libs_private`
=> Fix linking during .gir generation

bindings/gumjs/gumcmodule.c, bindings/gumjs/gumcmodule.h
Another fragment of https://github.com/frida/frida-gum/pull/511 ported to GObject, this time the following commits:
* [Split gum_cmodule_free_tcc](https://github.com/frida/frida-gum/pull/511/commits/7b9357d7526c972b37db89c023a1cd3a61aa2a3a)
* [Split gum_cmodule_link_tcc](https://github.com/frida/frida-gum/pull/511/commits/79f79d9299c984b77a3131db2637d9e3092e2f5a)
* [Split gum_add_defines from gum_cmodule_new_tcc](https://github.com/frida/frida-gum/pull/511/commits/41f56a07dedfc76de0b68b4c5601cd01872b1eae)
* [Add stub GCC CModule ops](https://github.com/frida/frida-gum/pull/511/commits/a87c91a2245112432f7b7cb2eb0c538ecab98e37)
=> GCC support in CModule [3/N]

bindings/gumjs/gumcmodule.c, tests/gumjs/script.c
Here are the rest of the original patches ported to GObject and tweaked a little bit according to my (hopefully) improved understanding of the code style. What remains is the testing part, right now one can apply
```
--- a/bindings/gumjs/gumcmodule.c
+++ b/bindings/gumjs/gumcmodule.c
@@ -81,6 +81,8 @@ gum_cmodule_new (const gchar * name,
const gchar * source,
GError ** error)
{
+  return gum_gcc_cmodule_new (source, error);
+
#ifdef HAVE_TINYCC
if (name == NULL || strcmp (name, "tcc") == 0)
return gum_tcc_cmodule_new (source, error);
```
to run the tests, but I think it should be possible to detect whether GCC is installed and run both TCC and GCC tests in this case.
=> GCC support in CModule [4/N]

gum/backend-darwin/gumcodesegment-darwin.c
Starting from iOS 14.3 on A12+ devices, `mach_vm_remap` can return `KERN_NO_SPACE` when the target vm map entries are marked as “permanent”.
It happens because `PMAP_CS` is enabled in the kernel, and all executable maps coming from the app itself and dyld have it enforced which also implies the maps are immutable (it is actually controlled by the `vm_map_executable_immutable` boot argument, which is `1` by default and can’t normally be changed).
This change detects and works around the issue by calling `mach_vm_protect` with the `VM_PROT_COPY` flag, to instruct the kernel to implicitly remap the target entries by removing the ”permanent” bit.
=> Handle permanent entries on darwin codesegment

bindings/gumjs/gumquickinstruction.c, bindings/gumjs/gumv8instruction.cpp
the `op->imm` field is a 64 bit value in both variants.
=> Fix Instruction operands parsing on x86

bindings/gumjs/runtime/cmodule/glib.h
Motivation: this is exactly the kind of common things which are sensibly faster when done from a CModule.
=> Expose base64 and checksum glib primitives to CModule

gum/backend-x86/gumstalker-x86.c
Call probes do not work on imported functions called through the GOT, as
these are indirect jumps with the target taken from the PLT.
Also considering direct jumps as candidates for call probes additionally
allows for call probes to be triggered when called as tail-calls.
This has a performance impact at compile-time on the stalker, but should
have no performance impact at run-time.
=> Stalker/x86: Also emit call probe on jmp insns

gum/backend-linux/gumandroid.c
In container environments such as anbox, the linker path in /proc/self/maps doesn't always map 1-to-1 with the actual linker path. This commit relaxes the matching of the linker by using a regex.
=> Relax android linker path matching

gum/backend-darwin/gumprocess-darwin.c, gum/gumdarwinmodule.c, gum/gumdarwinmodule.h, gum/gumprocess.h
In latest arm64e executables there are no binding opcodes, while usually the same information can be reconstructed by walking the metadata indexed by the LC_DYLD_CHAINED_FIXUPS command and stored in linkedit.
The problem in doing so on images which have already been loaded in memory by dyld is that the actual chains are lost because the bitfields in the slots have already been replaced by the actual pointers.
This change reconstructs the correct slots by scanning the pages of the segments which are pointed to by the fixups metadata and looking for pointers to resolved imports.
=> Enumerate darwin imports from chained fixups

config.h.in, gum/backend-elf/gumelfmodule.c, gum/backend-elf/gumelfmodule.h, meson.build
[Since Android Gradle plugin 3.6.0](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) `android:extractNativeLibs` is by default set to `false` which causes bundled native libraries (shared objects) to not be extracted to an extra file. Instead, Android extracts and loads them to memory at runtime.
As a consequence, frida cannot find these libraries under the given path and needs to extract them from the APK. Here is an example for such a path:
`/data/app/com.example.hellojni-G-r4G8zOhKSiGhnnvK7F0g==/base.apk!/lib/x86_64/libhello-jni.so`
Notice the apk path before the delimiting exclamation mark and the library path inside the zip after it.
This is related to 
- frida/frida#955
- frida/frida#1471 (though this needs fixing in Vala code)
- and …
=> Extract native libraries on android

bindings/gumjs/gumquickcore.c, bindings/gumjs/gumquickcore.h, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8core.h, bindings/gumjs/gumv8platform.cpp, gum/arch-arm/gumarmbacktracer.c, gum/arch-arm64/gumarm64backtracer.c, gum/arch-mips/gummipsbacktracer.c, gum/arch-x86/gumx86backtracer.c, gum/backend-darwin/gumdarwinbacktracer.c, gum/backend-dbghelp/gumdbghelpbacktracer.c, gum/backend-libunwind/gumunwbacktracer.c, gum/gumbacktracer.c, gum/gumbacktracer.h, libs/gum/heap/gumallocationtracker.c, libs/gum/heap/gumboundschecker.c, libs/gum/heap/gumcobjecttracker.c, tests/gumjs/script-fixture.c, tests/gumjs/script.c, tests/stubs/fakebacktracer.c
With this change, the `NativeCallback` js function is passed an instance of `CallbackContext` as the `this` argument.
This is an object with the `context` and `returnAddress` properties which, similarly to their counterparts found in `InvocationContext` for the `Interceptor` case, provide respectively a (minimal) CPU context and the address of the caller code.
The CPU context is minimal, in that it contains only what's needed to generate accurate backtraces, and it's read-only.
The primary use case for this addition is to provide a means for generating accurate meaningful backtraces from the context of swizzled ObjC methods (by using the `ObjC.implement()` api).
For this reason, this change also extends the Darwin (and Windows) accurate backtracer to take this case into account and …
=> Add minimal context to NativeCallback

gum/gumdarwingrafter.c
Not doing so triggers a bug in `codesign` for which the resulting signed binary turns out corrupted
=> Ensure merging binds doesn't make gaps in __LINKEDIT

gum/gumdarwingrafter.c
- make sure the contents of __LINKEDIT are contiguous (as per `codesign` requirement)
- make sure the code signature, if present, is left in a "good" position which is at the end of __LINKEDIT and starts aligned at 16 bytes
- when merging binds together, prevent the "addend" piece of state from bleeding into the merged lazy binds
- when lazy binds do not strictly follow binds, insert them just after the existing binds instead of putting them at the end of the file, to satisfy the code signature position constraints
=> Improve lazy binds merge logic

gum/gumdarwingrafter.c
Align to 16 bytes also when lazy binds follow regular binds
=> Fix DarwinGrafter alignment issue

bindings/gumjs/gumquickcore.c, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8interceptor.cpp
There was a regression in the tests starting from #578
Fixed getting wrong variable (v8), explicitly initializing new variables (qjs, v8)
=> gumjs: Fix v8 Interceptor context

gum/backend-darwin/gumobjcapiresolver.c
This change reduces the chances of crashing when any Objective-C class gets disposed during the lifetime of an `ApiResolver` instance of the `objc` type, by detecting and removing dangling class references.
=> objc-api-resolver: Guard against disposed objc classes

gum/arch-x86/gumx86reader.c, gum/arch-x86/gumx86reader.h, gum/arch-x86/gumx86writer.c, gum/backend-x86/gumstalker-x86.c, gum/gumstalker.c, gum/gumstalker.h, tests/core/arch-x86/stalker-x86.c
- Adjacency/Localtiy
- Split instrumented code into fast and slow slabs
- Compilation of adjacent blocks
- Use NOP slides rather than jumps to branch between adjacent instrumented blocks
- Move inline cache to the data slab
- Use linked list to track GumExecBlocks so data slab can also be used for inline caches
- Inline cache
- Replace shadow stack with inline cache on return
- Inline cache now uses Most Recently Used
- Unroll loop when searching inline cache
- Support backpatching inline cache for RET statements which return to the code slab 
- Perf
- Reduce branches when backpatching Jcc instructions
- Optimize generation of NOP padding.
- Emit UD2 after indirect JMP instructions to stall branch predictor.
- Misc
- Entry gates are no longer fast call (as they are on the slow path …
=> Stalker Performance Improvements

gum/backend-darwin/gumkernel-darwin.c, gum/backend-darwin/gumprocess-darwin-priv.h, gum/backend-darwin/gumprocess-darwin.c
Jailbreaks like Unc0ver and checkra1n store the kernel slide in `all_image_info_size`, obtainable via a call to `task_info` on the kernel task port. This change adds support for reconstructing the kernel base address from it.
=> kernel: Get base from all_image_info where supported

gum/arch-x86/gumx86relocator.c
Switch to jcc_short when jcc_near failed (-+2GB).
=> x86-relocator: fix Jccs

bindings/gumjs/gumquickcore.c, bindings/gumjs/gumquickcore.h, bindings/gumjs/gumquickkernel.c, bindings/gumjs/gumquickmemory.c, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8core.h, bindings/gumjs/gumv8kernel.cpp, bindings/gumjs/gumv8memory.cpp, bindings/gumjs/gumv8value.cpp, bindings/gumjs/runtime/core.js, gum/backend-darwin/gumkernel-darwin.c, gum/backend-linux/gumandroid.c, gum/backend-x86/gumstalker-x86.c, gum/gummemory-priv.h, gum/gummemory.c, gum/gummemory.h, tests/core/memory.c, tests/gumjs/script.c, vapi/frida-gum-1.0.vapi
In this PR:
* Allow `Memory.scan()` to scan for regex patterns, which is triggered automatically when the `pattern` argument is prefixed and suffixed with `/`, e.g. `/Some\s*Pattern/`. 
* Implement the `MatchPattern` object, whose constructor accepts either: a hexstring, `Memory.scan()`-style; or a regex pattern with the format above. This allows the user of the API to re-use a compiled regex, by keeping a reference to the `MatchPattern` object. 
* Make it return a `Promise<void>` instead of `void`.
* Make the `onComplete` callback optional (since we have the settling of the Promise to indicate that we're finished scanning.) 
* The API remains compatible with the older, callback-style one (except for one edge case, see below.)
Points for discussion:
* Is returning `Promise<void>` instead …
=> Add regex support to `Memory.scan()` and implement `MatchPattern` object

gum/backend-dbghelp/gumdbghelpbacktracer.c
Steps to reproduce the problem that this patch fixes:
1) Run notepad in Frida (x64).
2) Attach hook on combase!CoCreateInstance that prints backtrace onEnter (also load symbols for all modules..).
See truncated or invalid backtraces.
This patch also fixes the case when there are multiple hooks in a cascade, e.g. CreateFileInternal & CreateFileW. See the StackWalk loop.
The problem is that the code tries to skip the first frame by using the return address from the top of stack. SymWalk does not like this -- there is mismatch between XSP and XIP. StackWalk is sensitive about RIP, especially on x64.
It was tested with both 32-bit & 64-bit builds on Windows 10.
=> Fixing the case of SymWalk being sensitive about XIP.

bindings/gumjs/gumquickkernel.c, bindings/gumjs/gumquickmemory.c, bindings/gumjs/gumquickvalue.c, bindings/gumjs/gumquickvalue.h, bindings/gumjs/gumv8kernel.cpp, bindings/gumjs/gumv8memory.cpp, bindings/gumjs/gumv8value.cpp, bindings/gumjs/runtime/core.js, tests/gumjs/kscript.c
This makes the `Kernel.scan*()` API fully compatible with `Memory.scan*()`, which was [just updated](https://github.com/frida/frida-gum/pull/591) to add regex support.
TODO:
=> Implement `MatchPattern` qualifier and update `Kernel.scan*()`

gum/backend-darwin/gumobjcapiresolver.c, gum/backend-darwin/gumobjcdisposeclasspairmonitor.c, gum/backend-darwin/gumobjcdisposeclasspairmonitor.h, gum/meson.build
`GumObjcDisposeClassPairMonitor` uses the `Interceptor` to attach to `objc_disposeClassPair` so that on enter it locks a mutex, releasing it on leave.
This mutex is then used to protect the creation of the initial snapshot of Objective-C classes, and a cache-less reimplementation of `gum_objc_api_resolver_find_method_by_address`.
The monitor instance is shared across all concurrent usages, via the "obtain" semantics.
=> objc-api-resolver: Protect against objc_disposeClassPair via mutex

.clang-format, .clang-format-ignore, .clang-format-include, .github/workflows/ci.yml
This CI will run on master commits or pull requests to master.
It adds a clang-format configuration, but does not format the codebase. You must run `ninja -C build clang-format` first, and then uncomment the `ninja -C build clang-format-check` line.
---
Future follow-up improvements:
* Put all apt-get dependencies in a Docker build image and run inside that container
* Use ccache and cache the build folder for fast incremental build times
* Run tests on CI (requires fixing broken tests on Ubuntu when not building with the monorepo toolchain)
* Upload artifacts to GitHub (e.g. GIR)
=> Add CI and clang-format

gum/backend-arm/gumstalker-arm.c, gum/backend-arm64/gumstalker-arm64.c, gum/backend-mips/gumstalker-mips.c, gum/backend-x86/gumstalker-x86.c, gum/gumstalker.h
Expose some information about backpatch prefetches so that the caller can determine whether they relate to blocks which are present in its address space.
=> stalker: Add backpatch query support

.github/workflows/ci.yml, bindings/gumjs/gumquickfile.c, bindings/gumjs/gumv8file.cpp, tests/gumjs/script-fixture.c, tests/gumjs/script.c
Introducing some high-level static methods:
- readAllBytes(filePath: string): ArrayBuffer
- readAllText(filePath: string): string
- writeAllBytes(filePath: string, bytes: ArrayBuffer | number[]): void
- writeAllText(filePath: string, text: string): void
And some instance methods:
- tell(): number
- seek(offset: number, whence?: number): number
- readBytes(n?: number): ArrayBuffer
- readText(n?: number): string
- readLine(): string
With three new constants for `seek()`:
- File.SEEK_SET
- File.SEEK_CUR
- File.SEEK_END
=> gumjs: Extend the `File` API

.github/workflows/ci.yml, bindings/gumjs/gumquickscript.c, bindings/gumjs/gumquickscriptbackend.c, bindings/gumjs/gumscript.c, bindings/gumjs/gumscript.h, bindings/gumjs/gumscriptbackend.c, bindings/gumjs/gumscriptbackend.h, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8platform.cpp, bindings/gumjs/gumv8platform.h, bindings/gumjs/gumv8script-priv.h, bindings/gumjs/gumv8script.cpp, bindings/gumjs/gumv8scriptbackend.cpp, bindings/gumjs/gumv8scriptbackend.h, tests/gumjs/kscript-fixture.c, tests/gumjs/script-fixture.c, tests/gumjs/script.c, vapi/frida-gumjs-1.0.vapi
Instead of one Isolate shared between all scripts.
This will allow us to specify a custom startup snapshot per script.
=> gumjs: Move V8 backend to one Isolate per script

gum/backend-arm64/guminterceptor-arm64-glue.S
In this way is consistent with the latest changes where `nzcv` and all vector registers have been added to the arm64 cpu context.
=> arm64: update cpu context in glue prolog / epilog

gum/backend-darwin/gumdarwinmapper.c
The `GUM_ADVANCE_BY()` macro was missing a block scope. When it was used in the context of an `if()` also without scope, a misaligment could have occured between the `pc` and `cursor` offsets.
That happening on the chained symbols array of pointers could have caused the fixup processor to bind invalid pointers, leading to crashes.
When that happened while injecting `launchd`, it caused in turn a kernel panic on arm64e iOS.
=> darwin-mapper: Fix macro declaration

bindings/gumjs/gumquickinterceptor.c, bindings/gumjs/gumv8interceptor.cpp, gum/backend-arm/guminterceptor-arm.c, gum/backend-arm64/guminterceptor-arm64.c, gum/backend-x86/guminterceptor-x86.c, gum/guminterceptor-priv.h, gum/guminterceptor.c, gum/guminterceptor.h, tests/core/interceptor.c
I've only implemented for x86_64 as that's all I need right now, but the back-end changes are actually pretty minimal, so wouldn't be tricky to add to other architectures at all. On other architectures, `fast` Interceptor replacements just fall back to the standard implementation. 
I've not added any support for the `gumjs` bindings yet as again, I don't need right them now (and I had real trouble getting the HEAD to link properly with V8). But can't see it being too tricky. However, it might mean returning the NativePointer for the trampoline to the original function from the interceptor API (as fast interceptors don't support re-entrancy, so calling the original function from inside a hook will just result in an infinite loop). You'd probably want to change `Interceptor.replace` to do …
=> Added fast interceptor implementation for x86/64

bindings/gumjs/gumquicksymbol.c, gum/backend-darwin/gumdarwinsymbolicator.c, gum/backend-dbghelp/gumsymbolutil-dbghelp.c, gum/backend-libdwarf/gumsymbolutil-libdwarf.c, gum/gumreturnaddress.c, gum/gumreturnaddress.h, gum/gumsymbolutil.h, tests/core/backtracer.c
The `file_name` field is now an absolute path on Darwin too, the `column` field has also been added to all existing backends.
`file_name` is now also canonicalized in darwin and libdwarf backends.
=> debug-symbol: Ensure path is absolute and add column field

gum/gumdarwingrafter.c
- so that we can keep using a single instruction to reference data from code even in presence of many hooks / imports
- `gum_arm64_writer_put_ldr_reg_u64_ptr` is now checked for errors and the error is propagated
- no need to change the ABI because Interceptor is already consuming this correctly
=> gum-graft: Create multiple segments if needed

gum/backend-arm64/guminterceptor-arm64.c, gum/backend-darwin/gumdarwin.h, gum/backend-darwin/gumprocess-darwin.c
Also add `gum_darwin_query_protection()` as a very fast way to get the current page protection of any address on Darwin.
=> Interceptor: Flip page protection on Darwin grafted import activation

bindings/gumjs/generate-runtime.py
=> generate-runtime.py: Ignore symbols from tcclib.h

gum/backend-darwin/gumdarwinmapper.c
mach_vm_remap returns KERN_INVALID_ARGUMENT when given a size of 0.  Fix by skipping these segments.
=> darwin: Fix mapping zero-sized segments

gum/backend-arm64/guminterceptor-arm64.c
Fix ARMv8 BTI issue https://github.com/frida/frida/issues/2389
use `RET X16` instead of `BR X16` to bypass BTI
=> Fix ARMv8 BTI issue

gum/guminterceptor.c
In this way no thread can be left suspended, regardless of the initial ref count of the send right to its port.
=> interceptor: Keep thread port alive between suspend and resume on Darwin

gum/backend-arm64/guminterceptor-arm64.c
=> interceptor: Avoid BTI compatibility on arm64e

bindings/gumjs/gumquickmemory.c, bindings/gumjs/gumv8memory.cpp
Adds Memory.readVolatileByteArray to quickjs/v8. 
This uses `gum_memory_read` instead of `memcpy` used by Memory.readByteArray  to prevent os-exceptions on invalid memory addresses
=> gumjs: Add NativePointer#readVolatile()

bindings/gumjs/gumquickscript.c, bindings/gumjs/runtime/worker.js
This change contains two minor fixes:
- Fix typo in worker.js `_dispatchMessage()`
- so that `console.log` works from within the worker
- Pass `program` to worker's core init
- so that js exceptions can be generated without segfaulting
=> Improve worker

bindings/gumjs/gumquickdatabase.c, bindings/gumjs/gumquickfile.c, bindings/gumjs/gumquickmacros.h
This fixes the use case where `SQLiteDatabase` and `File` apis are used from within a Worker.
=> gumjs: Avoid segfault in file and database when Interceptor is not there

bindings/gumjs/gumquickvalue.c
Fix new NativePointer(number) for 32-bit BE architectures (e.g. ARM BE8).
This union which overlaps gpointer and int64_t fails to allow extraction of
gpointer when architecture is 32-bit big endian. For that combination padding
is required, which this patch adds only for that combination.
=> Fix NativePointer from number for 32-bit BE.

gum/backend-x86/gumstalker-x86.c, tests/core/arch-x86/stalker-x86.c
Adds a test and a fix allowing transformer to skip calls on x86, inspired by https://github.com/frida/frida-gum/commit/10160db8588051e87cecc94902c59846116be43a
=> Allow transformer to skip calls on x86

bindings/gumjs/gumquickprocess.c, bindings/gumjs/gumquickprocess.h, bindings/gumjs/gumv8process.cpp, bindings/gumjs/gumv8process.h, gum/backend-darwin/gumprocess-darwin.c, gum/backend-freebsd/gumprocess-freebsd.c, gum/backend-linux/gumprocess-linux.c, gum/backend-qnx/gumprocess-qnx.c, gum/backend-windows/gumprocess-windows.c, gum/gumprocess-priv.h, gum/gumprocess.c, gum/gumprocess.h
This returns a copy of the details of the module which represents the main executable of the process.
It is exposed to JS via the `Process.mainModule` property (where it's cached because the main module is constant during the process' lifetime).
For darwin this is implemented by getting the first loaded module for which the Mach-O header's `filetype` is set to `MH_EXECUTE`. For all other archs it is currently just the first loaded module (equivalent to `Process.enumerateModules()[0]`).
=> process: add get_main_module()

gum/guminterceptor.c
This prevents random `SIGBUS` crashes on Frida's own threads while using `Interceptor` to hook functions living in the same page as any of the ones potentially used internally.
=> interceptor: pause cloaked threads too

gum/arch-arm64/gumarm64reader.c, gum/arch-arm64/gumarm64reader.h, gum/backend-darwin/gumsymbolutil-darwin.c, gum/gumprocess.c, gum/gumprocess.h, vapi/frida-gum-1.0.vapi
There are 2 problems with the existing logic:
1. Since Xcode 15.1, when Xcode launches an app it places a software breakpoint (`brk` / `int3`) instruction at the beginning of the `notification_address` returned by `all_image_infos`. That's a function which the cache invalidator hooks with `Interceptor` in order to trigger when any libraries are loaded or unloaded at runtime. The problem with this approach is that in this way `Interceptor` relocates the breakpoint instruction, so when it gets executed Xcode can't match it with the address it expected, resulting into an uncaught exception crashing the app.
2. In cases where `Interceptor` can't work on system code (like the Gadget with `required` code-signing) the symbolicator cache is never invalidated
To overcome these problems what this …
=> Fix Darwin symbolicator cache invalidator logic

gum/backend-arm64/gumstalker-arm64.c
Instead of replacing them with functionally-equivalent ones, so that any pointer authentication context is used as expected.
=> stalker: copy register branch instructions on arm64

gum/backend-arm64/guminterceptor-arm64.c
This change is needed because since iOS 17, Xcode can load the `/private/preboot/Cryptexes/OS/usr/lib/libLogRedirect.dylib` library (there’s also a macOS counterpart:
`/System/Cryptexes/OS/usr/lib/libLogRedirect.dylib`) which uses interposing for wrapping a bunch of commonly used (and commonly hooked) symbols.
Since those libraries are not in the dyld cache, Frida was flagging them as non-system libraries, making Interceptor fail loudly (instead of silently) if no direct import grafts were found in the loaded binaries for those symbols.
This change adds a check for `/private/preboot` prefix, and now the prefix check is in OR with the dyld cache one instead of being mutually exclusive.
=> interceptor: Check lib prefix anyways in claiming grafts on arm64

bindings/gumjs/gumquickcloak.c, bindings/gumjs/gumquickcloak.h, bindings/gumjs/gumquickscript.c, bindings/gumjs/gumv8cloak.cpp, bindings/gumjs/gumv8cloak.h, bindings/gumjs/gumv8script-priv.h, bindings/gumjs/gumv8script.cpp, bindings/gumjs/meson.build, bindings/gumjs/runtime/core.js, gum/backend-arm64/guminterceptor-arm64.c, gum/gumcloak.c, tests/gumjs/script-fixture.c, tests/gumjs/script.c
This change adds the `Cloak` module, exposing the add / remove / query apis from `gumcloak.h`. This module is exposed to the Worker too.
There are 2 more loosely related changes:
- add a missing call to `gum_cloak_add_range` in Interceptor to cloak the thunks on arm64
- fix the docs of `gum_cloak_clip_range` to describe the actual semantics of the return value
=> Add Cloak module

bindings/gumjs/gumquickprocess.c, bindings/gumjs/gumv8process.cpp, gum/backend-darwin/gumprocess-darwin.c, gum/backend-freebsd/gumprocess-freebsd.c, gum/backend-linux/gumprocess-linux.c, gum/backend-qnx/gumprocess-qnx.c, gum/backend-windows/gumprocess-windows.c, gum/gumprocess.h, tests/core/process.c, tests/gumjs/script.c
Exposes thread names via `Process.enumerateThreads`.
Currently implemented:
Tested on iOS and Android, but not macOS + Linux yet.
=> process: Expose thread names via enumerate_threads()

bindings/gumjs/gumquickmemory.c, bindings/gumjs/gumv8memory.cpp, bindings/gumjs/gumv8value.cpp, bindings/gumjs/gumv8value.h, gum/backend-darwin/gummemory-darwin.c, gum/backend-freebsd/gummemory-freebsd.c, gum/backend-linux/gummemory-linux.c, gum/backend-qnx/gummemory-qnx.c, gum/backend-windows/gummemory-windows.c, gum/gummemory.h, tests/gumjs/script.c
This change adds `gum_memory_query_protection` which takes an address and returns the current protection for the page which contains it.
It is accessible from js bindings through `Memory.queryProtection()`.
On the Darwin backend it's a thin wrapper on top of `gum_darwin_query_protection`, on all other platforms it relies instead on the respective private implementations of `gum_memory_get_protection`.
=> Add Memory.queryProtection()

bindings/gumjs/gumquickprocess.c, bindings/gumjs/gumquickprocess.h, bindings/gumjs/gumv8process.cpp, bindings/gumjs/gumv8process.h, bindings/gumjs/runtime/core.js, gum/backend-arm/gumstalker-arm.c, gum/backend-arm64/gumstalker-arm64.c, gum/backend-mips/gumstalker-mips.c, gum/backend-x86/gumstalker-x86.c, gum/gumstalker-priv.h, gum/gumstalker.c, gum/gumstalker.h, tests/core/arch-arm/stalker-arm.c, tests/core/arch-arm64/stalker-arm64.c, tests/core/arch-x86/stalker-x86.c, tests/gumjs/script.c
Architecture specific code is based on `gum_stalker_infect`, so backend support is quite small. Support for x86, x64, arm and arm64 as well as QuickJS and V8. Includes supporting unit tests.
=> Add ability to run a function on a given thread

gum/backend-arm64/gumstalker-arm64.c
Stalker generates the block event even when those blocks have exclusive access. This may disrupt the exclusive access when a user handles the block event.
It seems that the default stalker event sinker uses spinlocks, which can starve the following thread.
[check this issue](https://github.com/frida/frida/issues/2769)
=> Fix: Stalker disrupts exclusive access by emitting a block event.

gum/backend-arm/gumspinlock-arm.c, gum/backend-arm64/gumspinlock-arm64.c, gum/backend-mips/gumspinlock-mips.c, gum/backend-x86/gumspinlock-amd64-msc.c, gum/backend-x86/gumspinlock-ia32-msc.c, gum/backend-x86/gumspinlock-x86.c, gum/gumcloak.c, gum/gumcloak.h, gum/guminterceptor.c, gum/guminterceptor.h, gum/gumspinlock.h, vapi/frida-gum-1.0.vapi
This also adds `gum_spinlock_try_acquire` which has the same semantics as `g_rec_mutex_trylock`.
=> Expose Cloak and Interceptor locks for usage in ThreadSuspendMonitor

bindings/gumjs/gumquickcore.c, bindings/gumjs/gumv8core.cpp, bindings/gumjs/gumv8core.h, bindings/gumjs/gumv8stalker.cpp, tests/gumjs/script.c
Fix for #789 : NativeCallback unable to leave thread's last error unchanged 
Though JavaScript function wrapped as a NativeCallback allows both inspecting and altering the current thread's system error, it wasn't possible to leave the system error as-is. Unless replaced by a value unequal to the original, the system error was being forced to 0 upon return from the NativeCallback. Fixed and tests added.
=> Fix: preserved thread's system error over NativeCallback invocations

gum/backend-posix/gumexceptor-posix.c
Add the SA_ONSTACK flag to handle situations where and alternative signal stack has been configured using `sigaltstack`. In the situations where no alternative stack was configured, this behaves as if the flag has not been set.
=> exceptor: Add SA_ONSTACK flag the POSIX backend

bindings/gumjs/runtime/message-dispatcher.js, tests/gumjs/script.c
Please see https://github.com/frida/frida-core/pull/525
=> Changes to support binary data on stdin and stdout

gum/backend-darwin/gumdarwinmoduleresolver.c
The patch for https://github.com/frida/frida/issues/2763
frida has stoppped working on iOS simulators for months, getting `module not found at "/usr/lib/libSystem.B.dylib"` error. The root cause is the logic for getting sysroot stops working.
Had some discussion with @mrmacete yesterday at 0x41con. We talked about reading env remotely, but surprisingly found the current implementation has a cheat to simply detect the location of `dyld_sim`. However the assumtion that `dyld_sim` is the first loaded image is no longer true. We need one more loop to initialize sysroot before putting them to the lookup table.
Also I believe this is the correct patch for https://github.com/frida/frida-swift-bridge/pull/18
Kudos to Francesco for helping me to set up the latest env and understand the source! 🙌
=> darwin: Fix sysroot on simulator

bindings/gumjs/gumquickcore.c, bindings/gumjs/gumv8core.cpp, tests/gumjs/script.c
This is a fix for #807 : recv wait can deadlock on an application thread.
See the issue description for a discussion of the root cause.
The proposed fix here operates by introducing a thread-local variable, `event_count_last_seen`. After entering the mutex, which ensures a stable reading of `core->event_count`, the thread enters the wait for `event_cond` only if `core->event_count` is equal to `event_count_last_seen`. In this way, we can guarantee that we won't begin waiting on `event_cond` at a time when the event we need has already been broadcast, which would produce the deadlock.
=> Fix #807: recv wait can deadlock on an application thread

bindings/gumjs/devkit/meson.build
This addresses a bug that _can_ result in gumjs being built before gum, and thus gumjs being incomplete (missing symbols).
This ensures that when building the gumjs devkit, gum is treated as an input.
=> Ensure gum is itself an input to the gumjs devkit

gum/arch-arm64/gumarm64writer.c, gum/backend-darwin/gumdarwinmapper.c
Fix a number of issues introduced in #709. Injecting a library using TLVs now works on iOS.
Tested on an iPhone 14 running iOS 16.2.1 with Dopamine.
=> Fix TLV initialization on AArch64

.github/workflows/ci.yml, bindings/gumjs/gumquickprocess.c, bindings/gumjs/gumquickprocess.h, bindings/gumjs/gumquickscript.c, bindings/gumjs/gumquickthread.c, bindings/gumjs/gumquickthread.h, bindings/gumjs/gumv8process.cpp, bindings/gumjs/gumv8process.h, bindings/gumjs/gumv8script-priv.h, bindings/gumjs/gumv8script.cpp, bindings/gumjs/gumv8thread.cpp, bindings/gumjs/gumv8thread.h, gum/backend-arm/gumprocess-arm.c, gum/backend-arm64/gumprocess-arm64.c, gum/backend-darwin/gumprocess-darwin.c, gum/backend-darwin/include/gum/gumdarwin.h, gum/backend-freebsd/gumprocess-freebsd.c, gum/backend-linux/gumprocess-linux.c, gum/backend-mips/gumprocess-mips.c, gum/backend-qnx/gumprocess-qnx.c, gum/backend-windows/gumexceptor-windows.c, gum/backend-windows/gumprocess-windows.c, gum/backend-windows/include/gum/gumwindows.h, gum/backend-x86/gumprocess-x86.c, gum/gumprocess-priv.h, gum/gumprocess.h, gum/meson.build, tests/gumjs/script.c, tests/run-linux-vm.sh, tests/vm.py
=> thread: Support hardware breakpoints and watchpoints

gum/gummemory.c, tests/gumjs/script.c
According to the docs of `g_regex_new` about the `G_REGEX_RAW` flag: "Usually strings must be valid UTF-8 strings, using this flag they are considered as a raw sequence of bytes."
The "strings" this refers to are the haystacks we then pass to `g_regex_match_full` when searching.
Without the flag, memory search with regex patterns can get interrupted before the range is over, when "invalid" bytes are encountered, resulting in false negatives.
=> memory: Make regex patterns raw

bindings/gumjs/gumquickmodule.c, bindings/gumjs/gumquickmodule.h, bindings/gumjs/gumquickscript-priv.h, bindings/gumjs/gumquickscript.c, bindings/gumjs/gumv8module.cpp, bindings/gumjs/gumv8module.h, gum/backend-darwin/gummodule-darwin.c, gum/backend-elf/gummodule-elf.c, gum/backend-elf/gummodule-elf.h
Our QuickJS suspend/resume patch isn't elaborate enough to support usage from finalizers. Given that modules are created and destroyed in waves, however, it's probably a bit on the expensive side to suspend/resume JS execution during the destruction of each value. So to avoid both issues we defer the unref using an idle source.
The better longer term solution will probably be to introduce a ModuleObserver of sorts that integrates with the platform's runtime loader and manages the lifetime of each Module. This will also allow us to emit signals anytime a Module is added/removed, which is a feature that a lot of agents would benefit from.
Kudos to @mrmacete for reporting.
=> gumjs: Fix crash in Module finalizers

gum/backend-linux/gummemory-linux.c, gum/backend-linux/gumprocess-linux.c, gum/backend-linux/include/gum/gumlinux.h
This PR optimizes the performance of gum_memory_read on Linux/Android platforms.
- gum_memory_read is significantly slow due to parsing memory maps on each call
- Memory.readVolatile using gum_memory_read is approximately 1000x slower than Memory.readByteArray
- Implement process_vm_readv for safe self-process memory reading on Linux kernels >= 3.2
- Add kernel version detection to ensure compatibility
```
let memPtr = Memory.alloc(4096);
let start = Date.now();
for(let i = 0; i < 10000; i++) {
Memory.readVolatile(memPtr, 4096);
}
let end = Date.now();
console.log(`readVolatile => elapsedTime: ${end - start} ms`);
start = Date.now();
for(let i = 0; i < 10000; i++) {
Memory.readByteArray(memPtr, 4096);
}
end = Date.now();
console.log(`readByteArray => elapsedTime: ${end - start} ms`);
``` …
=> memory: Optimize gum_memory_read for Linux/Android

gum/backend-linux/gummemory-linux.c
Related to PR #988
```
const memPtr = Memory.alloc(4096);
const module = new CModule(
`
#include <gum/gummemory.h>
void zero_memory(gpointer address, gsize size) {
guint8 zeros[4096] = {0};
gum_memory_write(address, zeros, size);
}
`,
{}
);
const zero_memory = new NativeFunction(module.zero_memory, 'bool', ['pointer','int']);
let start = Date.now();
for (let i = 0; i < 1000; i++) {
zero_memory(memPtr, 4096);
}
let end = Date.now();
console.log(`gum_memory_write => elapsedTime: ${end - start} ms`);
```
**Device:Android Pixel3a**
**frida-server:16.6.5**
gum_memory_write => elapsedTime: 4955 ms
**this version**
gum_memory_write => elapsedTime: 8 ms
=> memory: Optimize gum_memory_write for Linux/Android

bindings/gumjs/gumquickmemory.c, bindings/gumjs/gumv8memory.cpp, tests/gumjs/script.c
https://frida.re/news/2025/01/27/frida-16-6-6-released/
This PR implements the Memory.writeVolatile API that was previously documented but not implemented.
=> gumjs: Add NativePointer#writeVolatile()

gum/backend-darwin/gumdarwinmoduleresolver.c
An extra call to `g_ptr_array_unref` caused crashes due to memory corruption.
=> darwin: Fix double free in find_module_by_address

gum/backend-darwin/gumprocess-darwin.c
On recent iOS versions, the thread list pointer within the `pthread_from_mach_thread_np` function is referenced via ADRP + LDR instead of ADRP + ADD.
```
;-- _pthread_from_mach_thread_np:
0x20d7f1ee4      7f2303d5       pacibsp
0x20d7f1ee8      f44fbea9       stp x20, x19, [sp, -0x20]!
0x20d7f1eec      fd7b01a9       stp x29, x30, [sp, 0x10]
0x20d7f1ef0      fd430091       add x29, sp, 0x10
0x20d7f1ef4      f40300aa       mov x20, x0
0x20d7f1ef8      e0b52df0       adrp x0, segment.cache_map.75    ;
0x20d7f1efc      00100191       add x0, x0, 0x44                 ; this is the lock
0x20d7f1f00      a100a052       mov w1, 0x50000
0x20d7f1f04      3b22b594       bl stub._os_unfair_lock_lock_with_options
0x20d7f1f08      e8b52df0       adrp x8, segment.cache_map.75    ;
0x20d7f1f0c …
```
=> darwin: Update thread list pointer carving

gum/backend-darwin/gumdarwinmoduleresolver.c
This was a type confusion causing subtle crashes.
=> darwin: Fix module type in find_module_by_address

gum/backend-darwin/gumprocess-darwin.c
In this way any heap allocation is avoided, so there's no risk of deadlock in use cases like the Interceptor, where thread enumeration is used to suspend and resume threads by id.
=> darwin: Enumerate threads faster without flags

gum/guminterceptor.c
By storing the suspended thread ids into a `GumMetalArray` instead of a `GQueue` we prevent deadlocks when a suspended thread is holding the `dlmalloc` lock.
=> interceptor: Avoid heap allocation during suspend

bindings/gumjs/gumquickscriptbackend.c
Seems (at least for armbe8) that this magic used to detect QuickJS bytecode is `0x42`, not `0x02`? I've not found any docs on the QJS bytecode format, so I'm unsure why the value is different on this target architecture.
Otherwise, we hit the assert [here](https://github.com/frida/frida-gum/blob/dc7e51f2c721a80b1f2aa6dc7f7ad780483e76e1/bindings/gumjs/gumquickscriptbackend.c#L1269) whenever our tests call `gum_script_load_sync`, since this assert doesn't cause any effect in release builds, this undetected error results in a hang since we never handle the exception and notify the caller that the task has been completed. This error should maybe handled rather than an assert?
=> Fix `GUM_QUICKJS_BYTECODE_MAGIC`

README.md
Fixed Gum.Darwin.Mapper URL on README
=> Update README.md: fix Gum.Darwin.Mapper URL

gum/backend-linux/gumandroid.c, gum/backend-linux/gumprocess-linux.c, gum/backend-linux/include/gum/gumandroid.h
Hi,
This PR adds support to reading vector registers on aarch64 linux. I've tested it on Android 15 and works great.
It can be easily extended in future in order to implement other registers or bigger vector variants.
I've moved elf.h include from gumandroid.c to gumandroid.h as my IDE had problems with reading it via gumandroid.c, however the final effect should be the same.
I've omitted fpsr and fpcr as they don't seem to be used on other platforms.
=> cpu-context: implement neon on linux/arm64
