frida/frida-gum

- gum/arch-arm64/gumarm64writer.c
- gum/arch-arm64/gumarm64writer.h
This is needed for the arm64 fix in frida-core.
> Add gum_arm64_writer_put_add_reg_reg_reg function

- gum/gumscript-runtime-objc.js
It now does nothing if the number of classes hasn't changed.
> Optimize ObjC's ClassFactory.refresh

- gum/gumscriptcore.cpp
> Make creation ptr arithmetic functions more DRY

- gum/backend-qnx/gumprocess-qnx.c
Using info from reverse engineering the 'info meminfo' gdb command
implement improved enumeration of ranges (now with file names) and
implement enumeration of modules.
> Improve QNX enumerate_ranges and enumerate_modules

- gum/backend-qnx/gummemory-qnx.c
gum_try_mprotect includes special handling for the case
where an area cannot be marked PROT_WRITE because it is
a shared memory mapping which was opened read-only. This
appears to be the case for all .so code sections mapped.
The special handling includes remapping the necessary
areas in order to allow PROT_WRITE.
> Implement gum_try_mprotect and gum_clear_cache for QNX

- gum/Makefile.am
- gum/arch-arm/gumarmreader.c
- gum/arch-arm/gumarmreader.h
- gum/backend-arm/guminterceptor-arm.c
Two types of thunks are supported by this pull request:
- A simple branch immediate
- An indirect branch via a PC-relative lookup
> Implement _gum_interceptor_resolve_redirect for ARM

- gum/arch-arm/gumarmrelocator.c
- tests/core/arch-arm/armrelocator.c
Now correct for both dest_reg == src_reg and dest_reg != src_reg.
Also fixed test.
> Fix the pc relative add

- bindings/gumjs/gumscriptcore.cpp
- bindings/gumjs/gumscriptfile.cpp
- bindings/gumjs/gumscriptinterceptor.cpp
- bindings/gumjs/gumscriptmemory.cpp
- bindings/gumjs/gumscriptmodule.cpp
- bindings/gumjs/gumscriptprocess.cpp
- bindings/gumjs/gumscriptsocket.cpp
- bindings/gumjs/gumscriptstalker.cpp
- bindings/gumjs/gumscriptsymbol.cpp
- bindings/gumjs/gumscriptthread.cpp
Initial pass at docstrings & a small tweak to gum_script_memory_on_copy to match memcpy()
:smiley:
> Docstrings

- tests/gumjs/script-mac.m
Currently the second one doesn't pass.
> Add 2 ObjC tests

- bindings/gumjs/gumscript-runtime-objc.js
- bindings/gumjs/gumscriptcore.cpp
- tests/gumjs/script-mac.m
The test still fails, even though it works if I run it using `frida foo -l test.js` (replacing `send` with `console.log`).
> Fix all ObjC types

- bindings/gumjs/gumscriptcore.cpp
Fix for https://github.com/frida/frida-gum/issues/53.
> Zero-initialize retvalue

- bindings/gumjs/gumscript-runtime-core.js
Should we also handle it if there are modules with the same name?
> Process.getModuleByName(name) implemented

- bindings/gumjs/gumscript-runtime-dalvik.js
Example:
```
Dalvik.perform(function () {
Dalvik.choose("java.lang.String",
{
onMatch: function (instance) {
console.log(instance);
},
onError: function (reson) {
},
onComplete: function () {
console.log('Done.');
}
});
});
```
> Implemented 'Dalvik.choose(classname, callbacks);'

- gum/backend-qnx/gummemory-qnx.c
fopen/fread/fwrite might be buffered, open/read/write is not. This was causing an issue where there was a partial read when doing the 'copy on mprotect to write' in gum_try_mprotect.
> Switch from fopen to open for memory read/writes

- gum/backend-qnx/gummemory-qnx.c
Testing is a good idea. Not testing is not a good idea.
The move from fopen to open introduced bugs due to API incompatability. My not testing let those bugs get merged...
> Fix bugs introduced by PR #71

- bindings/gumjs/gumscript-runtime-objc.js
- tests/gumjs/script-darwin.m
- ObjC.nil
- ObjC.api: various ObjC runtime functions
- ObjC.Object.equals
- ObjC.Object.isNil
- ObjC.Object.$superClass
- ObjC.Object.$methods: list of methods prefixed with +/-
> Various ObjC improvements

- gum/guminterceptor.c
QNX has very small default stack sizes - just 128kb. This is insufficient
for V8 to run on top of. We've already patched glib and v8 to create new
threads with larger stacks, but that still leaves a problem with pre-existing
threads created by the target process. This patch works around this problem
by implementing a 'side-stack' which all the on_enter/on_leave handlers run
under instead of the original/real stack. This side-stack is sufficiently
large to run v8 code without issues (currently 2Mb).
> Implement side-stack for on_enter/on_leave on QNX

- bindings/gumjs/gumscriptmemory.cpp
- tests/gumjs/script.c
Memory.readFloat, Memory.writeFloat, Memory.readDouble and Memory.writeDouble added.
> Various 'Memory' operations added

- bindings/gumjs/gumscript-runtime-objc.js
Needed for autocompletion in repl
> Add getOwnPropertyNames property to ObjC.classes

- bindings/gumjs/gumscript-runtime-dalvik.js
- Replace 'var' with 'let', 'const'
- Replace function-expressions with function-declarations
- Add remaining Java modificators
- Insert missing and remove unnecessary semicolons
> Replace 'var' with 'let' or 'const' and some other modifcations

- bindings/gumjs/gumscript-runtime-dalvik.js
- Implement primitive arrays and objectarrays
- Refactored and renamed `typeFromClassName`
- Add function `env.getObjectRefType(obj)` to check for `objectRefType`
- Add method `env.checkForExceptionAndHandleIt()` and refactoring
> Implement primitive arrays, objectarrays and some smaller changes

- bindings/gumjs/gumscript-runtime-dalvik.js
- access to instance and static fields
- improve `getTypeName` and `getArrayTypeName`
- check if it's possible to cast
- instances can access static methods (now it's the same behavior as in Java)
- some other fixes
> Several adjustments

- bindings/gumjs/gumjs-babel-polyfill.js
The subset was generated using the following command in the core-js repo:
npm run grunt build:es6.promise,es6.symbol,es6.set,es6.array.from,es6.array.iterator,es7.array.includes,es6.array.find uglify
> Switch to a minimal subset of the babel polyfill.

- bindings/gumjs/generate-runtime.py
Resolves TypeError: can only concatenate list (not "map") to list
> Python 3.x build regression fix

- gum/Makefile.am
- gum/backend-darwin/gumtls-darwin.c
- gum/backend-posix/gumtls-posix.c
- gum/backend-qnx/gumtls-qnx.c
- gum/backend-windows/gumtls-windows.c
- gum/gum.c
- gum/guminterceptor.c
- gum/gumtls-priv.h
- tests/core/interceptor.c
> Implement temporary 'TLS' storage to work around malloc being called by pthread_setspecific

- gum/backend-arm64/gumstalker-arm64.c
> Compile error

- gum/backend-darwin/gumtls-darwin.c
reference: https://github.com/apple/darwin-xnu/blob/master/libsyscall/os/tsd.h#L122
> Fix tls_base calculation on arm64

- bindings/gumjs/gumdukeventsink.c
- bindings/gumjs/gumdukstalker.c
- bindings/gumjs/gumv8eventsink.cpp
- bindings/gumjs/gumv8stalker.cpp
- gum/backend-arm/gumstalker-arm.c
- gum/backend-arm64/gumstalker-arm64.c
- gum/backend-mips/gumstalker-mips.c
- gum/backend-x86/gumstalker-x86.c
- gum/gumeventsink.c
- gum/gumeventsink.h
- gum/gumstalker.h
- vapi/frida-gum-1.0.vapi
This PR adds a Stalker.flush() method that drains the queue.
Ref frida/frida-core#218.
> Add Stalker.flush().

- bindings/gumjs/runtime/message-dispatcher.js
Related to https://github.com/frida/frida/issues/696
> Improve RPC errors with custom fields

- gum/backend-x86/gumstalker-x86.c
- tests/core/arch-x86/stalker-x86.c
This works by detecting `jmp dword [Wow64Transition]` and then handling it like sysenter.
Fix https://github.com/frida/frida/issues/857
> Support Wow64Transition in Stalker

- gum/backend-posix/gummemory-posix.c
> Fix assert typo, changing 'length' to 'size'

- gum/gummemory.c
Fix for Issue #343, Segmentation fault by gum_memory_patch_code() with buffer exceed page size on ARM64
> Fix for segmentation fault by gum_memory_patch_code()

- bindings/gumjs/gumdukcore.c
- bindings/gumjs/gumv8core.cpp
- tests/gumjs/script.c
Improvement `NativeFunction` of support variadic function by issue #366.
> Improvement `NativeFunction` of support variadic function

- gum/backend-darwin/gumcodesegment-darwin.c
Because on iOS 13.x `mkstemps()` uses `arc4random()` and that
breaks os_unfair_lock when using Stalker.
> Use g_mkstemp() in place of mkstemps()

- gum/backend-linux/gumprocess-linux.c
With Yama LSM enabled processes by default can only ptrace their children (unless otherwise configured by sysctl). This appears to be the default setting on Ubuntu Linux. More aggressive changes may be required for other modes.
This patch uses prctl(PR_SET_PTRACER) to give permission to the ptracing thread (in another process) to attach.
- https://www.kernel.org/doc/Documentation/security/Yama.txt
- https://github.com/torvalds/linux/blob/master/security/yama/yama_lsm.c
Note also that Process.enumerateThreads() doesn't raise any exceptions on failure, instead simply returning an empty or reduced set. This may help to identify the cause if subsequent issues are raised. The following issues possibly relate:
- https://github.com/frida/frida/issues/489
- …
> Fix thread enumaration issue on Linux when using Yama

- gum/backend-linux/gumprocess-linux.c
Fix for https://github.com/frida/frida-gum/issues/373
> Fixes to auxilliary vector architecture detection

- gum/backend-elf/gumelfmodule.c
- gum/backend-elf/gumelfmodule.h
- gum/backend-linux/gumprocess-linux.c
Fix for https://github.com/frida/frida-gum/issues/414
> Fix Linux module enumeration when invoked through loader

- bindings/gumjs/gumv8interceptor.cpp
- bindings/gumjs/gumv8value.cpp
In this way v8’s behaviour is consistent with duktape’s one.
> Skip optional undefined args in v8

- gum/backend-arm/gumstalker-arm.c
- tests/core/arch-arm/stalker-arm.c
> Suppress Stalker ARM32 events around exclusive ops

- gum/arch-arm/gumthumbrelocator.c
- gum/backend-arm/gumstalker-arm.c
- tests/core/arch-arm/stalker-arm-fixture.c
- tests/core/arch-arm/stalker-arm.c
> Fix Stalker ARM handling of Thumb-2 'mov pc, <reg>'

- tests/core/arch-arm/stalker-arm.c
> Fix Stalker ARM tests clobber callee saved registers

- gum/gumdefs.h
> Fix capstone endianness on ARM BE8

- gum/backend-libdwarf/gumsymbolutil-libdwarf.c
Fix incorrect calculation of nearest symbol.
> Fix incorrect calculation of nearest symbol.

- bindings/gumjs/gumcmodule.c
- bindings/gumjs/gumcmodule.h
- bindings/gumjs/gumquickcmodule.c
- bindings/gumjs/gumv8cmodule.cpp
- tests/gumjs/script.c
Hi! I finally managed to wrap my head around GObject. This patch is a rewrite of https://github.com/frida/frida-gum/pull/511/commits/8775940ad25bedd48baf2817db645d2bc4a6170d, which enables adding new compiler backends in addition to TCC.
> GCC support in CModule [2/N]

- gum/backend-linux/gumprocess-linux.c
Closes https://github.com/frida/frida/issues/1710
> Fix enumerating modules with spaces on path

- bindings/gumjs/generate-runtime.py
- bindings/gumjs/gumjs-common.props
- bindings/gumjs/gumquickcore.c
- bindings/gumjs/gumv8core.cpp
- bindings/gumjs/gumv8platform.cpp
- bindings/gumjs/gumv8platform.h
- bindings/gumjs/package.json
- bindings/gumjs/runtime/core.js
- bindings/gumjs/runtime/error-handler-quickjs.js
- bindings/gumjs/runtime/error-handler-v8.js
- bindings/gumjs/runtime/swift.js
> Bundle frida-swift-bridge 🎉

- bindings/gumjs/gumquickprocess.c
- bindings/gumjs/gumv8process.cpp
- tests/gumjs/script.c
> gumjs: Add Process getters for cwd, home, and tmp dirs

- bindings/gumjs/runtime/console.js
Copied the API from the web standards
> Add console.count and console.countReset methods

- bindings/gumjs/gumquickinterceptor.c
- bindings/gumjs/gumv8interceptor.cpp
- bindings/gumpp/interceptor.cpp
- gum/backend-arm64/gumstalker-arm64.c
- gum/backend-darwin/gumexceptor-darwin.c
- gum/backend-posix/gumexceptor-posix.c
- gum/backend-x86/gumstalker-x86.c
- gum/guminterceptor.c
- gum/guminterceptor.h
- libs/gum/heap/gumboundschecker.c
- tests/core/arch-x86/stalker-x86.c
- tests/core/interceptor-darwin.c
- tests/core/interceptor.c
Followup on: https://github.com/frida/frida-rust/issues/44
> Interceptor: Provide original function address back to caller

- gum/backend-arm64/asmdefs.h
- gum/backend-arm64/memcpy-advsimd.S
- gum/gumlibc.c
- gum/meson.build
Based on profiling of large data transfers.
> arm64: Fix gum_memcpy() / gum_memmove() performance

- bindings/gumjs/gumquickcore.c
- bindings/gumjs/gumv8core.cpp
- tests/gumjs/script.c
Setting this when constructing a `NativeFunction` will prevent both `Interceptor` and `Stalker` from triggering when it is called.
> gumjs: Add support for 'none' code trap option

- bindings/gumjs/generate-runtime.py
> Fix loading unicode strings

- meson.build
part of https://github.com/frida/frida-core/pull/452
> meson: Require Frida fork of V8

- bindings/gumjs/gumquickcore.c
- bindings/gumjs/gumquickcore.h
- bindings/gumjs/gumquickinterceptor.c
- bindings/gumjs/gumv8core.cpp
- bindings/gumjs/gumv8core.h
- bindings/gumjs/gumv8interceptor.cpp
- gum/guminterceptor.c
- gum/guminterceptor.h
- tests/gumjs/script.c
Also when Interceptor isn't involved.
> gumjs: Always expose thread's system error to NativeCallback

- gum/backend-linux/gumprocess-linux.c
I apologize for any inconvenience previously caused.
I have corrected it, how do you like it?
(sorry I am not familiar with git.)
https://github.com/frida/frida-gum/pull/1008
> gum: fix ptrace error handling to propagate errors on failure
